<?php

return [
    'uz' => [
        'help' => "Ushbu bot uchun mavjud buyruqlar:\n- /start - Bot bilan muloqotni boshlash\n- /help - Ushbu yordam xabarini ko'rsatish\n- /set_threshold [raqam] - Spam ovoz berish chegarasini o'rnatish (faqat adminlar uchun)\n- /toggle_cleanup - Guruhga qo'shilish/chiqish xabarlarini tozalashni yoqish/o'chirish (faqat adminlar uchun)\n- /spam - Xabarni spam deb xabar berish (unga javob berish orqali)\n- /lang [uz|en|ru] - Guruh tilini o'zgartirish\n\nXususiyatlari:\n- Ushbu bot yoqilgan bo'lsa, qo'shilish/chiqish xabarlarini avtomatik ravishda o'chirib yordam beradi.\n- Havolali xabarlar uchun spam ovoz berishni boshlaydi.\n- Guruh a'zolari 👍 yoki 👎 tugmalari orqali ovoz berishlari mumkin.\n- Agar spam ovozi chegaraga yetsa, xabar avtomatik ravishda o'chiriladi.",
        'cleanup_enabled' => "Guruhga qo'shilish/chiqish xabarlarini tozalash yoqildi.",
        'cleanup_disabled' => "Guruhga qo'shilish/chiqish xabarlarini tozalash o'chirildi.",
        'admin_only' => "Ushbu sozlamani o'zgartirish uchun admin bo'lishingiz kerak.",
        'is_spam_query' => "Ushbu xabar spam deb o'ylaysizmi?",
        'spam_report_reply' => "Iltimos, /spam buyrug'idan foydalanib spam deb belgilamoqchi bo'lgan xabarga javob bering.",
        'start_in_group' => "Guruhda /start qabul qilindi. Ruxsatlar tekshirilmoqda...",
        'user_is_admin' => "Foydalanuvchi admin.",
        'bot_is_admin' => "Bot admin.",
        'all_set' => "Hammasi tayyor! ✅",
        'settings_initialized' => "Guruh uchun sozlamalar boshlandi. Hammasi tayyor! ✅",
        'only_admins_configure' => "Faqat guruh adminlari botni sozlashi mumkin.",
        'make_me_admin' => "Iltimos, meni guruhda admin qiling, men guruhni boshqarishga yordam beraman.",
        'error_fetching_admins' => "Adminlarni olishda xatolik yuz berdi: ",
        'usage_threshold' => "Foydalanish: /set_threshold [raqam]",
        'threshold_set' => "Spam chegarasi %d ga o'rnatildi.",
        'already_voted' => "Siz ushbu xabarga ovoz bergansiz.",
        'spam_deleted' => "Xabar spam deb hisoblandi va o'chirildi. Ovoz berganlarga rahmat: %s.",
        'vote_status' => "Ushbu xabar spammi?\n\n👍 - %d ovoz\n👎 - %d ovoz",
        'error_vote_data' => "Xatolik: Ovoz ma'lumotlarini olib bo'lmadi.",
        'user_badge_reach' => "<a href=\"tg://user?id=%d\">Ushbu foydalanuvchi</a> %s darajasiga yetgani bilan tabriklaymiz!",
        'error_user_points' => "Xatolik: Foydalanuvchi ochkolarini olib bo'lmadi.",
        'lang_changed' => "Bot tili %s ga o'zgartirildi.",
        'usage_lang' => "Foydalanish: /lang [uz|en|ru]",
        'group_only' => "Ushbu buyruq faqat guruhlarda amal qiladi.",
    ],
    'en' => [
        'help' => "Here are the available commands for this bot:\n- /start - Start interacting with the bot\n- /help - Display this help message\n- /set_threshold [number] - Set the spam vote threshold (admin only)\n- /toggle_cleanup - Toggle join/leave message cleanup in the group (admin only)\n- /spam - Report a message as spam by replying to it\n- /lang [uz|en|ru] - Change the group language\n\nFeatures:\n- This bot helps clean up the group by automatically deleting join/leave messages when enabled.\n- It initiates voting for messages with links to decide if they should be marked as spam and deleted.\n- Group members can vote using 👍 or 👎 buttons on such messages.\n- If the spam vote threshold is reached, the message will be deleted automatically.",
        'cleanup_enabled' => "Join/leave message cleanup has been enabled.",
        'cleanup_disabled' => "Join/leave message cleanup has been disabled.",
        'admin_only' => "You must be an admin to toggle this setting.",
        'is_spam_query' => "Do you think this message is spam?",
        'spam_report_reply' => "Please reply to the message you want to mark as spam using /spam.",
        'start_in_group' => "Received /start in the group. checking permissions...",
        'user_is_admin' => "User is an admin.",
        'bot_is_admin' => "Bot is an admin.",
        'all_set' => "You're all set! ✅",
        'settings_initialized' => "Settings initialized for the group. You're all set! ✅",
        'only_admins_configure' => "Only group admins can configure the bot.",
        'make_me_admin' => "Please make me an admin in the group, I can help you control the group.",
        'error_fetching_admins' => "Error fetching chat administrators: ",
        'usage_threshold' => "Usage: /set_threshold [number]",
        'threshold_set' => "Spam threshold has been set to %d.",
        'already_voted' => "You have already voted on this message.",
        'spam_deleted' => "The message was counted as spam and has been deleted. Thanks to voters: %s.",
        'vote_status' => "Do you think it is spam?\n\n👍 - %d votes\n👎 - %d votes",
        'error_vote_data' => "Error: Could not fetch vote data.",
        'user_badge_reach' => "Kudos to <a href=\"tg://user?id=%d\">this user</a> for reaching the level of %s!",
        'error_user_points' => "Error: Could not fetch user points.",
        'lang_changed' => "Bot language has been changed to %s.",
        'usage_lang' => "Usage: /lang [uz|en|ru]",
        'group_only' => "This command is only available in group chats.",
    ],
    'ru' => [
        'help' => "Доступные команды для этого бота:\n- /start - Начать взаимодействие с ботом\n- /help - Показать это справочное сообщение\n- /set_threshold [число] - Установить порог голосования за спам (только для админов)\n- /toggle_cleanup - Переключить очистку сообщений о входе/выходе (только для админов)\n- /spam - Сообщить о спаме, ответив на сообщение\n- /lang [uz|en|ru] - Изменить язык группы\n\nОсобенности:\n- Этот бот помогает очищать группу, автоматически удаляя сообщения о входе/выходе, когда это включено.\n- Он инициирует голосование для сообщений со ссылками, чтобы решить, следует ли пометить их как спам и удалить.\n- Участники группы могут голосовать с помощью кнопок 👍 или 👎.\n- Если порог голосов за спам достигнут, сообщение будет удалено автоматически.",
        'cleanup_enabled' => "Очистка сообщений о входе/выходе включена.",
        'cleanup_disabled' => "Очистка сообщений о входе/выходе выключена.",
        'admin_only' => "Вы должны быть администратором, чтобы изменить этот параметр.",
        'is_spam_query' => "Как вы думаете, это сообщение является спамом?",
        'spam_report_reply' => "Пожалуйста, ответь to на сообщение, которое вы хотите пометить как спам, используя /spam.",
        'start_in_group' => "Получено /start в группе. Проверка разрешений...",
        'user_is_admin' => "Пользователь является администратором.",
        'bot_is_admin' => "Бот является администратором.",
        'all_set' => "Все готово! ✅",
        'settings_initialized' => "Настройки инициализированы для группы. Все готово! ✅",
        'only_admins_configure' => "Только администраторы группы могут настраивать бота.",
        'make_me_admin' => "Пожалуйста, сделайте меня администратором в группе, я помогу вам контролировать группу.",
        'error_fetching_admins' => "Ошибка при получении администраторов чата: ",
        'usage_threshold' => "Использование: /set_threshold [число]",
        'threshold_set' => "Порог спама установлен на %d.",
        'already_voted' => "Вы уже проголосовали за это сообщение.",
        'spam_deleted' => "Сообщение было расценено как спам и удалено. Спасибо проголосовавшим: %s.",
        'vote_status' => "Считаете ли вы это спамом?\n\n👍 - %d голосов\n👎 - %d голосов",
        'error_vote_data' => "Ошибка: не удалось получить данные голосования.",
        'user_badge_reach' => "Поздравляем <a href=\"tg://user?id=%d\">этого пользователя</a> за достижение уровня %s!",
        'error_user_points' => "Ошибка: не удалось получить очки пользователя.",
        'lang_changed' => "Язык бота изменен на %s.",
        'usage_lang' => "Использование: /lang [uz|en|ru]",
        'group_only' => "Эта команда доступна только в групповых чатах.",
    ],
];
